/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme/lyricstapperTheme.ts
 * Command: astryx theme build app/theme/lyricstapperTheme.ts --out app/theme/lyricstapperTheme.generated.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
