/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme/lyricstapperTheme.ts
 * Command: astryx theme build app/theme/lyricstapperTheme.ts --out app/theme/lyricstapperTheme.generated.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

/// <reference path="./lyricstapper.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const lyricstapperTheme: DefinedTheme;
